sudo: required
language: generic
matrix:
  include:
  - os: linux
    dist: trusty
    env:
    - VERSION=7
    - BUILD_ARCHITECTURE=x86_64
  - os: osx
    osx_image: xcode9.2
    language: generic
global:
  env:
  - PROJECT=TaskFlow
  - PROJECT_TEMPLATE=latest
install:
- source /dev/stdin <<< "$(curl -s https://raw.githubusercontent.com/Zefiros-Software/ZPM/dev/script/install-zpm.sh)"
script:
- cd test && zpm run test-definition TaskFlow
notifications:
  slack:
    secure: fVJl9F/1pUm7farKTLpby9NGx1r9QgjH+c2T6+xenUCn4ZHuzmHLPjtk/XxuaRkwvcQTSyEsx2WA2faurqWsSOZM/S+lWdBPxWJLru4JCK9nE3L4Spp2+cQWWjecIxK4arlAm+8QQJVTHvqwCBfqQMfaOn076c3w99YOspAFfsYrLQjT3eqLEpT1n2W+R2XnKU8sNlepTncaleqmf4EhK+OEyqsxaFyKOF6zHhCfkywYTuxic8Dv3NDK3/iivOl9TDpV3QAQ0p2jzBcq2YuyMGZPebBAAUHO864QjhYwmowwsKNhUTm+II3v2RciPxuEjKWsE6haz+/TrQCMiTTaCFyKJ7Y/FcjmQmoWWmlWmc70PAKb345Rgr2AwkbA5fB0MnIa4JKyvyu+CYamXj1mTXeZxBdsW0WGsNpgaCka+oYK82NWUkqi1jVQig4Tco4KohuKcEZoYqFGzmdHZwZYCI4IzARlsYWUhBnlKh5eqq67/VnE5RYoEh3jyAP4EgrhIWSZESHmvSD21l7CQu5JTwkZHJbwMilJ5GA6kQkfenQ4bBXlt96hESEpNkusRlUv1/tmmjxRhVORIbqqAyi2IJCVXMP4Gp1R8rvxd/s9oxuVzectWbXDJnEBwLeyN52FrMWWM6zZ4eVrLCxyKdRu3/w2XpsuaqH/5HRl2futn20=
